# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hw3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hw3.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\thw3.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x14Multiplication_input\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"$\n\x15Multiplication_output\x12\x0b\n\x03res\x18\x01 \x01(\x05\"\x1b\n\x0bSquare_data\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"9\n\x04\x41rgs\x12\x0e\n\x06x_coor\x18\x01 \x03(\x02\x12\x0e\n\x06y_coor\x18\x02 \x03(\x02\x12\x11\n\tn_cluster\x18\x03 \x01(\x05\"\x17\n\x05\x43olor\x12\x0e\n\x06\x63olors\x18\x01 \x03(\x05\x32\xbe\x01\n\x03HW3\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x44\n\x11RpcMultiplication\x12\x15.Multiplication_input\x1a\x16.Multiplication_output\"\x00\x12)\n\tRpcSquare\x12\x0c.Square_data\x1a\x0c.Square_data\"\x00\x12\x1c\n\tRpcKmeans\x12\x05.Args\x1a\x06.Color\"\x00\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=41,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=72,
)


_MULTIPLICATION_INPUT = _descriptor.Descriptor(
  name='Multiplication_input',
  full_name='Multiplication_input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='Multiplication_input.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='Multiplication_input.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=124,
)


_MULTIPLICATION_OUTPUT = _descriptor.Descriptor(
  name='Multiplication_output',
  full_name='Multiplication_output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='Multiplication_output.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=162,
)


_SQUARE_DATA = _descriptor.Descriptor(
  name='Square_data',
  full_name='Square_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Square_data.data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=191,
)


_ARGS = _descriptor.Descriptor(
  name='Args',
  full_name='Args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_coor', full_name='Args.x_coor', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_coor', full_name='Args.y_coor', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_cluster', full_name='Args.n_cluster', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=250,
)


_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colors', full_name='Color.colors', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=275,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Multiplication_input'] = _MULTIPLICATION_INPUT
DESCRIPTOR.message_types_by_name['Multiplication_output'] = _MULTIPLICATION_OUTPUT
DESCRIPTOR.message_types_by_name['Square_data'] = _SQUARE_DATA
DESCRIPTOR.message_types_by_name['Args'] = _ARGS
DESCRIPTOR.message_types_by_name['Color'] = _COLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

Multiplication_input = _reflection.GeneratedProtocolMessageType('Multiplication_input', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPLICATION_INPUT,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:Multiplication_input)
  })
_sym_db.RegisterMessage(Multiplication_input)

Multiplication_output = _reflection.GeneratedProtocolMessageType('Multiplication_output', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPLICATION_OUTPUT,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:Multiplication_output)
  })
_sym_db.RegisterMessage(Multiplication_output)

Square_data = _reflection.GeneratedProtocolMessageType('Square_data', (_message.Message,), {
  'DESCRIPTOR' : _SQUARE_DATA,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:Square_data)
  })
_sym_db.RegisterMessage(Square_data)

Args = _reflection.GeneratedProtocolMessageType('Args', (_message.Message,), {
  'DESCRIPTOR' : _ARGS,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:Args)
  })
_sym_db.RegisterMessage(Args)

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), {
  'DESCRIPTOR' : _COLOR,
  '__module__' : 'hw3_pb2'
  # @@protoc_insertion_point(class_scope:Color)
  })
_sym_db.RegisterMessage(Color)



_HW3 = _descriptor.ServiceDescriptor(
  name='HW3',
  full_name='HW3',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=278,
  serialized_end=468,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='HW3.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RpcMultiplication',
    full_name='HW3.RpcMultiplication',
    index=1,
    containing_service=None,
    input_type=_MULTIPLICATION_INPUT,
    output_type=_MULTIPLICATION_OUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RpcSquare',
    full_name='HW3.RpcSquare',
    index=2,
    containing_service=None,
    input_type=_SQUARE_DATA,
    output_type=_SQUARE_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RpcKmeans',
    full_name='HW3.RpcKmeans',
    index=3,
    containing_service=None,
    input_type=_ARGS,
    output_type=_COLOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HW3)

DESCRIPTOR.services_by_name['HW3'] = _HW3

# @@protoc_insertion_point(module_scope)
